export const RouteName = {
  Home: 'Home',
  Welcome: 'Welcome',
  Login: 'Login',
  Register: 'Register',
  ForgotPassword: 'ForgotPassword',
  ResetPassword: 'ResetPassword',
  Profile: 'Profile',
  Settings: 'Settings',
  About: 'About',
  Contact: 'Contact',
  Terms: 'Terms',
  Privacy: 'Privacy',
  FAQ: 'FAQ',
  Help: 'Help',
  Support: 'Support',
  Feedback: 'Feedback',
  ContactUs: 'ContactUs',
  Chat: 'Chat',
  ChatList: 'ChatList',
  ChatRoom: 'ChatRoom',
} as const;
